config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :admin do
    root 'dashboards#index'
    resources :users
    resources :shops
    resources :tags
    resources :areas
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    get 'prefectures/:prefecture_id/areas', to: 'prefecture_areas#index', as: :prefecture_areas
  end

  resources :password_resets, only: %i[create edit update]
  resource :password_resets, only: :new

  get 'prefectures/:prefecture_id/areas', to: 'areas#index', as: :prefecture_areas

  resources :shop_locations, only: :index

  resources :shops, only: %i[index show], shallow: true do
    resources :reviews
    resources :shop_tags, path: :tags, only: %i[index create destroy], as: :tags
    resources :favorites, only: :create
  end

  resources :favorites, only: %i[index destroy]

  post 'reviews/:review_id/nices', to: 'nices#create', as: :review_nices
  resources :nices, only: :destroy

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  resources :users, only: :create do
    resource :profile, only: :show
  end
  resource :user, only: :destroy

  get 'users/:user_id/reviews', to: 'user_reviews#index', as: :user_reviews

  resource :profile, only: %i[edit update]

  get 'my_page', to: 'my_pages#index'

  resources :contacts, only: %i[new create]

  get 'signup', to: 'users#new'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  root 'static_pages#index'
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :area
  has_one :prefecture, through: :area
  has_many :reviews, dependent: :destroy
  has_many :shop_tags
  has_many :tags, through: :shop_tags, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites, dependent: :destroy

  validates :area_id, presence: true
  validates :name, presence: true, uniqueness: { scope: :address }
  validates :address, presence: true
  validates :url, format: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/
  with_options presence: true,
               numericality: { greater_than_or_equal_to: -999.999999, less_than_or_equal_to: 999.999999 }, format: { with: /\A-?\d{1,3}(\.\d{1,6})?\z/ } do
    validates :latitude
    validates :longitude
  end
  validates :int_average, presence: true, numericality: { in: 0..5 }
  validates :eqcust_average, presence: true, numericality: { in: 0..5 }
  validates :sofr_average, presence: true, numericality: { in: 0..5 }

  scope :by_int_average, ->(int_av) { where('int_average >= ?', int_av) }
  scope :by_eqcust_average, ->(eqcust_av) { where('eqcust_average >= ?', eqcust_av) }
  scope :by_sofr_average, ->(sofr_av) { where('sofr_average >= ?', sofr_av) }
  scope :name_or_address_contain, ->(word) { where('shops.name LIKE ?', "%#{word}%").or(where('address LIKE ?', "%#{word}%")) }
  scope :by_prefecture_id, lambda { |prefecture_id|
    joins(:area)
      .where(area: { prefecture_id: })
  }
  scope :by_area_id, ->(area_id) { where(area_id:) }
  scope :by_tag_ids, lambda { |tag_ids|
    joins(:shop_tags)
      .where(shop_tags: { tag_id: tag_ids })
      .group(:id)
      .having('COUNT(*) = ?', tag_ids.length.to_i)
  }
  EARTH_RADIUS = 6378.137
  scope :nearby, lambda { |latitude, longitude, distance_in_km|
    select("shops.*,
            (#{EARTH_RADIUS} * acos(cos(radians(#{latitude}))
            * cos(radians(latitude))
            * cos(radians(longitude) - radians(#{longitude}))
            + sin(radians(#{latitude}))
            * sin(radians(latitude)))) AS distance")
      .where("(#{EARTH_RADIUS} * acos(cos(radians(#{latitude}))
            * cos(radians(latitude))
            * cos(radians(longitude) - radians(#{longitude}))
            + sin(radians(#{latitude}))
            * sin(radians(latitude)))) <= ?", distance_in_km)
      .order('distance ASC')
  }
  scope :sort_by_int, -> { reorder(int_average: :desc) }
  scope :sort_by_eqcust, -> { reorder(eqcust_average: :desc) }
  scope :sort_by_sofr, -> { reorder(sofr_average: :desc) }
  scope :sort_by_id, -> { reorder(id: :asc) }
  scope :sort_by_distance, -> { reorder('distance ASC') }

  def reviewed?
    reviews.exists?(user_id: current_user.id)
  end

  def add_tag(tag)
    tags << tag
  end

  def remove_tag(tag)
    tags.delete(tag)
  end

  def tagged?(tag)
    tags.exists?(id: tag.id)
  end

  def update_rating_averages
    update_average(:minimal_interaction, :int_average, :int_unspecified)
    update_average(:equipment_customization, :eqcust_average, :eqcust_unspecified)
    update_average(:solo_friendly, :sofr_average, :sofr_unspecified)
  end

  def self.average_attributes
    %i[int_average eqcust_average sofr_average]
  end

  def self.averages_select_options
    [['★☆☆☆☆ 以上', 1],
     ['★★☆☆☆ 以上', 2],
     ['★★★☆☆ 以上', 3],
     ['★★★★☆ 以上', 4],
     ['★★★★★', 5]]
  end

  private

  def update_average(review_attr, shop_attr, exclude_attr)
    calculatable_reviews = reviews.where.not(review_attr => exclude_attr)
    new_average = if calculatable_reviews.present?
                    calculatable_reviews.average(review_attr)
                  else
                    0
                  end
    update!(shop_attr => new_average)
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < Admin::BaseController
  before_action :set_shop, only: %i[show edit update destroy]

  def index
    @shops = Shop.all.includes(:area, :prefecture).order(created_at: :desc).page(params[:page]).per(25)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to admin_shops_path, success: t('defaults.flash_message.created', item: Shop.model_name.human)
    else
      flash.now[:error] = t('defaults.flash_message.not_created', item: Shop.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @shop.update(shop_params)
      redirect_to admin_shop_path(@shop), success: t('defaults.flash_message.updated', item: Shop.model_name.human)
    else
      flash.now[:error] = t('defaults.flash_message.not_updated', item: Shop.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @shop.destroy!
    redirect_to admin_shops_path, status: :see_other, success: t('defaults.flash_message.deleted', item: Shop.model_name.human)
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:area_id, :name, :address, :phone_number, :url, :opening_hours, :latitude, :longitude)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_before_action :require_login

  def index
    if search_shops_params.blank?
      redirect_to shop_locations_path
    else
      search_shops
      respond_to do |format|
        format.html
        format.json { render json: @all_shops }
      end
    end
  end

  def show
    @shop = Shop.find(params[:id])
    gon.shop = @shop
    @reviews = @shop.reviews.order(updated_at: :desc).limit(5)
  end

  private

  def search_shops
    @search_shops_params = search_shops_params
    @sort_shops_params = sort_shops_params
    @search_shops_form = SearchShopsForm.new(@search_shops_params)
    @all_shops = @search_shops_form.search
    @all_shops_json = @all_shops.to_json
    @shops = sort_shops(@all_shops).includes(:tags, :favorites).page(params[:page])
    set_center_of_map
  end

  def set_center_of_map
    if @search_shops_params[:latitude].present?
      @center_lat = @search_shops_params[:latitude]
      @center_lng = @search_shops_params[:longitude]
    else
      @center_lat = @all_shops.first&.latitude
      @center_lng = @all_shops.first&.longitude
    end
    @zoom = if @search_shops_params[:latitude].present?
              13
            elsif @search_shops_params[:area_id].present?
              12
            else
              9
            end
  end

  def sort_shops(relation)
    return relation if sort_shops_params.blank?

    case sort_shops_params[:key]
    when 'int'
      relation.sort_by_int
    when 'eqcust'
      relation.sort_by_eqcust
    when 'sofr'
      relation.sort_by_sofr
    when 'distance'
      relation.sort_by_distance
    else
      relation.sort_by_id
    end
  end

  def sort_shops_params
    params[:sort]&.permit(:key)
  end

  def search_shops_params
    params[:q]&.permit(:words, :area_id, :prefecture_id, :int_average, :eqcust_average, :sofr_average, :latitude, :longitude, tag_ids: [])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def search_query(search_shops_params)
    return pref_and_area(search_shops_params) if search_shops_params[:prefecture_id].present?
    return words(search_shops_params) if search_shops_params[:words].present?
    return '近く' if search_shops_params[:latitude].present?

    t('defaults.all')
  end

  private

  def pref_and_area(search_shops_params)
    pref = Prefecture.find_by(id: search_shops_params[:prefecture_id])&.name
    area = Area.find_by(id: search_shops_params[:area_id])&.name
    return "#{pref} #{area}" if area

    pref
  end

  def words(search_shops_params)
    "「#{search_shops_params[:words]}」"
  end

  def sort_shops_options(search_shops_params)
    options = { t('.unspecified') => 'id', t('.int_desc') => 'int', t('.eqcust_desc') => 'eqcust', t('.sofr_desc') => 'sofr' }
    options['現在地に近い順'] = 'distance' if search_shops_params[:latitude] && search_shops_params[:longitude]
    options
  end
end

app/views/shops/_fav_buttons.html.erb
<% if current_user.favorite?(shop) %>
  <%= render 'shops/unfavorite', shop: shop %>
<% else %>
  <%= render 'shops/favorite', shop: shop %>
<% end %>

app/views/shops/_favorite.html.erb
<%= link_to shop_favorites_path(shop), id: "fav-button-for-shop-#{shop.id}", data: {turbo_method: :post} do %>
  <i class="fa-regular fa-heart text-red-400"></i>
<% end %>

app/views/shops/_latest_reviews.html.erb
<% if shop.reviews.present? %>
  <div class="reviews flex flex-col gap-y-4">
    <%= render partial:'reviews/review_summary', collection: reviews, as: :review %>
  </div>
  <div class="text-center mt-6">
    <%= link_to t('.show_all_reviews'), shop_reviews_path(shop), class: 'btn btn-primary' %>
  </div>
<% else %>
  <div class="no_reviews text-center">
    <p><%= t '.no_reviews' %></p>
  </div>
<% end %>

app/views/shops/_rating_field_for_index.html.erb
<div class="grid grid-cols-[3fr_2fr]">
  <div class="text-center pr-1 bg-base-200 rounded-lg">
    <%= Shop.human_attribute_name(field) %>
  </div>
  <div class="pl-1">
    <% if shop.send("#{field}") == 0 %>
      評価なし
    <% else %>
      <span class="rating rating-sm">
        <% 5.times do |n| %>
          <%= radio_button_tag "shop_#{shop.id}[#{field}]", n + 1, shop.send("#{field}") == n + 1, { disabled: true, class: "mask mask-star-2 bg-orange-400 cursor-default" } %>
        <% end %>
      </span>
    <% end %>
  </div>
</div>

app/views/shops/_rating_field_for_shop.html.erb
<div class="text-sm text-right">
  <p>
    <%= Shop.human_attribute_name(field) + ': ' %>
    <% if shop.send("#{field}") == 0 %>
      評価なし
    <% else %>
      <span class="rating rating-sm">
        <% 5.times do |n| %>
          <%= radio_button_tag "shop_#{shop.id}[#{field}]", n + 1, shop.send("#{field}") == n + 1, { disabled: true, class: "mask mask-star-2 bg-orange-400 cursor-default" } %>
        <% end %>
      </span>
    <% end %>
  </p>
</div>

app/views/shops/_rating_field_for_show.html.erb
<div>
  <div class="flex justify-center w-3/4 mx-auto bg-base-200 rounded-lg">
    <%= Shop.human_attribute_name(field) %>
    <%= render 'shared/tooltip_icon', description: description %>
  </div>
  <div class="w-3/4 mx-auto flex justify-center pt-1">
    <% if shop.send("#{field}") == 0 %>
      <div>評価なし</div>
    <% else %>
      <div class="rating">
        <% 5.times do |n| %>
          <%= radio_button_tag "shop_#{shop.id}[#{field}]", n + 1, shop.send("#{field}") == n + 1, { disabled: true, class: "mask mask-star-2 bg-orange-400 cursor-default" } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/_rating_for_index.html.erb
<div class="grid grid-cols-[4fr_2fr]">
  <div class="text-center pr-1 bg-primary/30 rounded-full">
    <%= Shop.human_attribute_name(field) %>
  </div>
  <div class="pl-1">
    <% if shop.send("#{field}") == 0 %>
      評価なし
    <% else %>
      <span class="rating rating-sm">
        <% 5.times do |n| %>
          <%= radio_button_tag "shop_#{shop.id}[#{field}]", n + 1, shop.send("#{field}") == n + 1, { disabled: true, class: "mask mask-star-2 bg-orange-400 cursor-default" } %>
        <% end %>
      </span>
    <% end %>
  </div>
</div>

app/views/shops/_search_form_for_shops.html.erb
<div class="card shrink-0 w-full max-w-md md:max-w-fit mx-auto shadow-2xl bg-base-100">
  <%= form_with model: search_shops_form, scope: :q, url: shops_url, method: :get, html: { data: { turbo_frame: 'shops-list' } }, class: 'card-body p-6' do |f| %>
    <%= f.hidden_field :prefecture_id %>
    <%= f.hidden_field :area_id %>
    <%= f.hidden_field :words %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
    <%= hidden_field_tag 'sort[key]', sort_shops_params[:key] %>

    <div class="preferences">
      <div class="title mb-4">
        <h2 class="card-title">
          <%= t('defaults.preferences') %>
        </h2>
      </div>

      <div class="preferences-body md:flex">
        <div class="rating_averages md:grid md:flex-grow md:mb-4">
          <% Shop.average_attributes.each do |attr| %>
            <div class="average_items form-control">
              <div class="flex">
                <%= f.label attr, Shop.human_attribute_name(attr), class: 'label' %>
                <%= render 'shared/tooltip_icon', description: t("defaults.description.#{attr}") %>
              </div>
              <%= f.select attr, Shop.averages_select_options, { include_blank: t('defaults.unspecified') }, class: 'select select-bordered select-sm select-primary' %>
            </div>
          <% end %>
        </div>

        <div class="divider divider-horizontal"></div>

        <div class="md:grid md:flex-grow">
          <div class="tags form-control flex flex-col gap-y-1 my-4 md:my-auto md:mx-auto">
            <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, { include_hidden: false } do |b| %>
              <div class="tag">
                <%= b.check_box class: 'checkbox checkbox-sm checkbox-accent align-middle' %>
                <%= b.label class: 'align-middle' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center mt-6 md:mt-4">
      <%= button_tag(type: 'submit', class: 'btn btn-accent btn-wide') do %>
        <i class="fa-solid fa-magnifying-glass"></i>
        <%= t('defaults.search') %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shops/_shop.html.erb
<% content_for :javascript_includes do %>
  <%= include_gon %>
  <%= javascript_include_tag 'map_on_shops_show', "data-turbo-track": "reload" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_API_KEY"]}&callback=initMap", async: true, defer: true %>
<% end %>

<div class="card bg-primary/10 mx-auto w-full my-6 shadow-xl">
  <div class="card-body p-6">
    <% if current_user %>
      <div class="fav-button text-lg text-right h-auto">
        <%= render 'fav_buttons', shop: shop %>
      </div>
    <% end %>

    <div class="area text-xs text-right">
      <%= shop.area.name %>
    </div>

    <h2 class="card-title text-lg">
      <%= shop.name %>
    </h2>

    <div class="tags">
      <% shop.tags.each do |tag| %>
        <div class="badge badge-accent badge-sm">
          <%= tag.name %>
        </div>
      <% end %>
      <%= link_to t('defaults.edit_tags'), shop_tags_path(shop), class: 'inline-block link link-accent text-xs', data: { turbo: false } %>
    </div>

    <div class="rating-averages">
      <div class="indicator w-full">
        <span class="indicator-item indicator-bottom indicator-center badge badge-secondary badge-sm rounded"><%= t('defaults.preferences_rating') %></span>
        <div class="flex flex-col w-full mx-2 gap-y-4 mt-4 px-2 pt-2 pb-6 bg-base-100/50 border border-secondary border-dotted rounded-lg">
          <%= render 'rating_for_show', shop: shop, field: :int_average, description: t("defaults.description.int_average") %>
          <%= render 'rating_for_show', shop: shop, field: :eqcust_average, description: t("defaults.description.eqcust_average") %>
          <%= render 'rating_for_show', shop: shop, field: :sofr_average, description: t("defaults.description.sofr_average") %>
        </div>
      </div>
    </div>

    <div id="map" class="h-[350px] md:h-[600px] mt-6"></div>

    <div class="static-informations mx-auto space-y-4 px-2 mt-6">
      <div class="attribute grid grid-cols-[1fr_8fr]">
        <div>
          <i class="fa-solid fa-location-dot"></i>
        </div>
        <div>
          <%= simple_format(shop.address) %>
        </div>
      </div>

      <div class="attribute grid grid-cols-[1fr_8fr]">
        <div>
          <i class="fa-solid fa-phone"></i>
        </div>
        <div>
          <%= link_to shop.phone_number, "tel:#{shop.phone_number}", class: 'link md:pointer-events-none md:no-underline' %>
        </div>
      </div>

      <div class="attribute grid grid-cols-[1fr_8fr]">
        <div>
          <i class="fa-solid fa-clock"></i>
        </div>
        <div>
          <%= simple_format(shop.opening_hours) %>
        </div>
      </div>
    </div>

    <%= render 'shop_buttons', shop: shop %>
  </div>
</div>

app/views/shops/_shop_buttons.html.erb
<div class="card-actions justify-center mt-6">
  <%= link_to t('defaults.to_official_site'), shop.url, class: 'btn btn-primary', target: '_blank' %>
  <%= render 'shared/review_button', shop: shop %>
</div>

app/views/shops/_shop_for_index.html.erb
<%= link_to shop_path(shop), data: {turbo: false} do %>
  <div class="card bg-base-100 mx-auto w-full my-6 shadow-lg active:bg-base-200" ontouchstart="">
    <div class="card-body p-6">
      <h2 class="card-title text-lg">
        <%= shop.name %>
      </h2>

      <div class="tags">
        <% shop.tags.each do |tag| %>
          <div class="badge badge-secondary badge-sm">
            <%= tag.name %>
          </div>
        <% end %>
      </div>

      <div class="rating_averages flex flex-col mx-auto p-3 gap-y-1 mt-3 text-sm">
        <%= render 'rating_for_index', shop: shop, field: :int_average %>
        <%= render 'rating_for_index', shop: shop, field: :eqcust_average %>
        <%= render 'rating_for_index', shop: shop, field: :sofr_average %>
      </div>

      <div class="static-informations mx-auto px-2 mt-3 text-sm">
        <div class="address grid grid-cols-[1fr_8fr]">
          <div>
            <i class="fa-solid fa-location-dot"></i>
          </div>
          <div>
            <%= simple_format(shop.address) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shops/_shop_for_show.html.erb
<div class="card bg-base-100 mx-auto w-full my-6 shadow-xl">
  <div class="card-body p-6">
    <div class="area text-xs text-right">
      <%= shop.area.name %>
    </div>

    <h2 class="card-title text-lg">
      <%= shop.name %>
    </h2>

    <div class="tags">
      <% shop.tags.each do |tag| %>
        <div class="badge badge-secondary badge-sm">
          <%= tag.name %>
        </div>
      <% end %>
      <%= link_to t('defaults.edit_tags'), shop_tags_path(shop), class: 'inline-block link link-accent text-xs', data: { turbo: false } %>
    </div>

    <div class="rating_averages flex flex-col gap-y-4 mt-4 p-2">
      <%= render 'rating_for_show', shop: shop, field: :int_average, description: t("defaults.description.int_average") %>
      <%= render 'rating_for_show', shop: shop, field: :eqcust_average, description: t("defaults.description.eqcust_average") %>
      <%= render 'rating_for_show', shop: shop, field: :sofr_average, description: t("defaults.description.sofr_average") %>
    </div>

    <div class="static-informations mx-auto space-y-4 px-2 mt-4">
      <div class="attribute grid grid-cols-[1fr_8fr]">
        <div>
          <i class="fa-solid fa-location-dot"></i>
        </div>
        <div>
          <%= simple_format(shop.address) %>
        </div>
      </div>

      <div class="attribute grid grid-cols-[1fr_8fr]">
        <div>
          <i class="fa-solid fa-phone"></i>
        </div>
        <div>
          <%= link_to shop.phone_number, "tel:#{shop.phone_number}", class: 'link md:pointer-events-none md:no-underline' %>
        </div>
      </div>

      <div class="attribute grid grid-cols-[1fr_8fr]">
        <div>
          <i class="fa-solid fa-clock"></i>
        </div>
        <div>
          <%= simple_format(shop.opening_hours) %>
        </div>
      </div>
    </div>

    <%= render 'shop_buttons', shop: shop %>
  </div>
</div>

app/views/shops/_shop_summary.html.erb
<div class="card bg-primary/10 mx-auto w-full my-6 shadow-lg">
  <div class="card-body p-6">
    <% if current_user %>
      <div class="fav-button text-right text-lg mt-0">
        <%= render 'shops/fav_buttons', shop: shop %>
      </div>
    <% end %>

    <h2 class="card-title text-lg">
      <%= shop.name %>
    </h2>

    <div class="tags">
      <% shop.tags.each do |tag| %>
        <div class="badge badge-accent badge-sm">
          <%= tag.name %>
        </div>
      <% end %>
    </div>

    <div class="rating_averages">
      <div class="indicator w-full">
        <span class="indicator-item indicator-bottom indicator-center badge badge-secondary badge-sm rounded"><%= t('defaults.preferences_rating') %></span>
        <div class="flex flex-col mx-auto gap-y-1 text-sm px-3 pt-3 pb-4 mt-3 rounded-lg border border-dotted border-secondary">
          <%= render 'shops/rating_for_index', shop: shop, field: :int_average %>
          <%= render 'shops/rating_for_index', shop: shop, field: :eqcust_average %>
          <%= render 'shops/rating_for_index', shop: shop, field: :sofr_average %>
        </div>
      </div>
    </div>

    <div class="static-informations md:mx-20 px-2 mt-5 text-sm">
      <div class="address grid grid-cols-[1fr_9fr] md:grid-cols-[1fr_15fr]">
        <div>
          <i class="fa-solid fa-location-dot"></i>
        </div>
        <div>
          <%= simple_format(shop.address) %>
        </div>
      </div>
    </div>

    <div class="card-actions justify-center mt-4">
      <%= link_to t('defaults.show'), shop_path(shop), data: {turbo: false}, class: 'btn btn-primary btn-wide' %>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<% content_for :title, t('.title') %>
<% content_for :javascript_includes do %>
  <%= include_gon %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_API_KEY"]}&callback=initMap", async: true, defer: true %>
  <%= javascript_include_tag 'map_on_shops_index', "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'sort_shops', "data-turbo-track": "reload", type: "module" %>
<% end %>

<div class="title mb-8">
  <h1 class="font-bold text-2xl text-neutral text-center">
    <%= t('.title') %>
  </h1>
  <h2 class="font-bold text-xl text-neutral text-center mt-6">
    <%= t('.subtitle', query: search_query(@search_shops_params)) %>
  </h2>
</div>

<div class="flex flex-col w-full border-opacity-50">
  <%= render 'search_form_for_shops', search_shops_form: @search_shops_form, sort_shops_params: @sort_shops_params %>
  <%= render 'sort_shops_options', url: shops_path, search_shops_params: @search_shops_params, sort_shops_params: @sort_shops_params %>
  <%= turbo_frame_tag 'shops-list' do %>
    <div class="divider mt-4 text-sm">
      <%= @all_shops.length %>件
    </div>
    <% if @shops.present? %>
      <div id="map-container" data-shops="<%= @all_shops_json %>" data-lat="<%= @center_lat %>" data-lng="<%= @center_lng %>" data-zoom="<%= @zoom %>">
        <div id="map" class="h-[350px] md:h-[600px] mt-6"></div>
      </div>
      <%= render partial: 'shop_summary', collection: @shops, as: :shop %>
      <%= render 'shared/pagination', object: @shops %>
    <% else %>
      <p class="text-center"><%= t '.no_shops' %></p>
    <% end %>
  <% end %>
</div>