config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :admin do
    root 'dashboards#index'
    resources :users
    resources :shops
    resources :tags
    resources :areas
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    get 'prefectures/:prefecture_id/areas', to: 'prefecture_areas#index', as: :prefecture_areas
  end

  resources :password_resets, only: %i[create edit update]
  resource :password_resets, only: :new

  get 'prefectures/:prefecture_id/areas', to: 'areas#index', as: :prefecture_areas

  resources :shop_locations, only: :index

  resources :shops, only: %i[index show], shallow: true do
    resources :reviews
    resources :shop_tags, path: :tags, only: %i[index create destroy], as: :tags
    resources :favorites, only: :create
  end

  resources :favorites, only: %i[index destroy]

  post 'reviews/:review_id/nices', to: 'nices#create', as: :review_nices
  resources :nices, only: :destroy

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  resources :users, only: :create do
    resource :profile, only: :show
  end
  resource :user, only: :destroy

  get 'users/:user_id/reviews', to: 'user_reviews#index', as: :user_reviews

  resource :profile, only: %i[edit update]

  get 'my_page', to: 'my_pages#index'

  resources :contacts, only: %i[new create]

  get 'signup', to: 'users#new'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  root 'static_pages#index'
end

app/views/shared/_before_login_header.html.erb
<div class="navbar bg-base-100 sticky top-0 z-10 shadow-xl">
  <div class="flex-1 px-2">
    <%= link_to root_path, class: 'btn btn-ghost p-0' do %>
      <%= image_tag 'logo_long_text_and_stars.png', class: 'h-12 rounded-md' %>
    <% end %>
  </div>

  <div class="flex justify-end flex-1 px-2">
    <div class="flex items-center gap-x-2">
    <!-- ボタンが１つなら↑は消していいかも -->
      <%= link_to t('user_sessions.new.title'), login_path, class: 'btn btn-ghost text-primary' %>
      <details class="dropdown dropdown-end">
        <summary class="btn btn-ghost rounded-btn">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </summary>
        <ul class="p-2 shadow menu dropdown-content z-[1] bg-base-100 rounded-box w-52">
          <li>
            <%= link_to t('shops.index.title'), shop_locations_path %>
          </li>
          <li>
            <%= link_to t('users.new.title'), signup_path %>
          </li>
          <li>
            <%= link_to t('defaults.contact'), new_contact_path %>
          </li>
        </ul>
      </details>
    </div>
  </div>
</div>

app/views/shared/_edit_and_delete_buttons.html.erb
<% if logged_in? && current_user.own?(review) %>
  <div class="w-full flex justify-end gap-1 text-lg" ontouchstart="">
    <%= link_to edit_review_path(review), class: 'px-1.5 rounded text-secondary active:bg-base-200' do %>
      <i class="fa-solid fa-pencil"></i>
    <% end %>
    <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: 'px-1.5 rounded text-secondary active:bg-base-200' do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation" class="bg-error text-red-500 p-2 rounded-lg mt-3 text-sm">
      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'success' %>
    <div role="alert" class="alert alert-success w-5/6 mx-auto max-w-screen-md mt-2 flex justify-center" >
      <i class="fa-regular fa-circle-check" style="color: #0e110d;"></i>
      <span>
        <%= message %>
      </span>
    </div>
  <% else %>
    <div role="alert" class="alert alert-error w-5/6 mx-auto max-w-screen-md mt-2 flex justify-center" >
      <i class="fa-regular fa-circle-xmark" style="color: #0e110d;"></i>
      <span>
        <%= message %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-neutral text-neutral-content">
  <aside ontouchstart="">
    <div class="flex gap-x-3">
      <p>
        <%= link_to t('defaults.contact'), new_contact_path, class: 'link link-hover' %>
      </p>
      <p>
        <%= link_to t('defaults.terms'), terms_path, class: 'link link-hover' %>
      </p>
      <p>
        <%= link_to t('defaults.privacy_policy'), privacy_policy_path, class: 'link link-hover' %>
      </p>
    </div>
    <div class="text-xs">Copyright © ヒトカラナビ</div>
  </aside>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100 sticky top-0 z-10 shadow-xl">
  <div class="flex-1 px-2">
    <%= link_to root_path, class: 'btn btn-ghost p-0' do %>
      <%= image_tag 'logo_long_text_and_stars.png', class: 'h-12 rounded-md' %>
    <% end %>
  </div>

  <div class="flex justify-end flex-1 px-2">
    <div class="flex items-center gap-x-2">
      <%= link_to current_user.name, my_page_path, class: 'btn btn-ghost text-xs break-all max-w-28 md:max-w-none p-1' %>
      <details class="dropdown dropdown-end">
        <summary class="btn btn-ghost rounded-btn">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </summary>
        <ul class="p-2 shadow menu dropdown-content z-[1] bg-base-100 rounded-box w-52">
          <li>
            <%= link_to t('shops.index.title'), shop_locations_path %>
          </li>
          <li>
            <%= link_to t('my_pages.index.title'), my_page_path %>
          </li>
          <li>
            <%= link_to t('defaults.contact'), new_contact_path %>
          </li>
          <li>
            <%= link_to t('defaults.logout'), logout_path, data: {turbo_method: :delete} %>
          </li>
        </ul>
      </details>
    </div>
  </div>
</div>

app/views/shared/_line_login_button.html.erb
<%= link_to 'LINEでユーザー登録/ログイン', auth_at_provider_path(provider: :line), class: 'btn bg-line-green hover:bg-line-green-hover active:bg-line-green-active text-white w-full' %>

app/views/shared/_pagination.html.erb
<div class="flex justify-center mt-8">
  <%= paginate object, window: 1 %>
</div>

app/views/shared/_review_button.html.erb
      <% if logged_in? && current_user.reviewed?(shop) %>
        <%= link_to simple_format(t('defaults.show_my_review')), review_path(shop.reviews.find_by(user_id: current_user.id)), class: 'btn btn-primary', data: { turbo: false } %>
      <% else %>
        <%= link_to t('defaults.post_review'), new_shop_review_path(shop), class: 'btn btn-accent', data: { turbo: false } %>
      <% end %>

app/views/shared/_tooltip_icon.html.erb
<div class="tooltip tooltip-primary before:max-w-56 before:content-[attr(data-tip)] inline-block content-center ml-2" data-tip="<%= description %>">
  <i class="fa-solid fa-circle-question fa-sm text-primary"></i>
</div>

app/views/shared/_user_name_with_rank.html.erb
<%= user.name %>
<% if !user.regular? %>
  <span class="<%= user_rank_color(user) %>">
    <i class="fa-solid fa-crown"></i>
  </span>
<% end %>