config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :admin do
    root 'dashboards#index'
    resources :users
    resources :shops
    resources :tags
    resources :areas
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    get 'prefectures/:prefecture_id/areas', to: 'prefecture_areas#index', as: :prefecture_areas
  end

  resources :password_resets, only: %i[create edit update]
  resource :password_resets, only: :new

  get 'prefectures/:prefecture_id/areas', to: 'areas#index', as: :prefecture_areas

  resources :shop_locations, only: :index

  resources :shops, only: %i[index show], shallow: true do
    resources :reviews
    resources :shop_tags, path: :tags, only: %i[index create destroy], as: :tags
    resources :favorites, only: :create
  end

  resources :favorites, only: %i[index destroy]

  post 'reviews/:review_id/nices', to: 'nices#create', as: :review_nices
  resources :nices, only: :destroy

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  resources :users, only: :create do
    resource :profile, only: :show
  end
  resource :user, only: :destroy

  get 'users/:user_id/reviews', to: 'user_reviews#index', as: :user_reviews

  resource :profile, only: %i[edit update]

  get 'my_page', to: 'my_pages#index'

  resources :contacts, only: %i[new create]

  get 'signup', to: 'users#new'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  root 'static_pages#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :shop_tags
  has_many :shops, through: :shop_tags, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  before_action :set_tag, only: %i[show edit update destroy]

  def index
    @tags = Tag.all.order(id: :asc).page(params[:page]).per(25)
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, success: t('defaults.flash_message.created', item: Tag.model_name.human)
    else
      flash.now[:error] = t('defaults.flash_message.not_created', item: Tag.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @tag.update(tag_params)
      redirect_to admin_tag_path(@tag), success: t('defaults.flash_message.updated', item: Tag.model_name.human)
    else
      flash.now[:error] = t('defaults.flash_message.not_updated', item: Tag.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy!
    redirect_to admin_tags_path, status: :see_other, success: t('defaults.flash_message.deleted', item: Tag.model_name.human)
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/admin/tags/_form.html.erb
<div class="card shrink-0 w-full max-w-lg mx-auto shadow-2xl bg-base-100">
  <%= form_with(model: tag, url: url, class: 'card-body') do |form| %>
    <%= render 'shared/error_messages', object: form.object %>

    <div class="form-control">
      <%= form.label :name, class: 'label' %>
      <%= form.text_field :name, class: "input input-bordered input-primary w-full max-w-lg" %>
    </div>

    <div class="form-control mt-6 text-center">
      <%= form.submit class: 'btn btn-accent' %>
    </div>
  <% end %>
</div>

app/views/admin/tags/_tag.html.erb
<tr>
  <th><%= tag.id %></th>
  <td><%= tag.name %></td>
  <td>
    <%= link_to t('defaults.show'), admin_tag_path(tag), class: 'btn btn-sm' %>
    <%= render 'admin/shared/edit_and_delete_buttons', edit_path: edit_admin_tag_path(tag), delete_path: admin_tag_path(tag) %>
  </td>
</tr>

app/views/admin/tags/edit.html.erb
<% content_for :title, t('.title') %>

<%= render 'form', tag: @tag, url: admin_tag_url(@tag) %>
<%= render 'admin/shared/to_index_button', model_name: Tag.model_name.human, path: admin_tags_path %>

app/views/admin/tags/index.html.erb
<% content_for :title, t('.title') %>

<%= render 'admin/shared/to_new_button', model_name: Tag.model_name.human, path: new_admin_tag_path %>
<div class="overflow-x-auto">
  <table class="table">
    <thead>
      <tr>
        <th><%= Tag.human_attribute_name(:id) %></th>
        <th><%= Tag.human_attribute_name(:name) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @tags %>
    </tbody>
  </table>
</div>
<%= render 'admin/shared/pagination', object: @tags %>

app/views/admin/tags/new.html.erb
<% content_for :title, t('.title') %>

<%= render 'form', tag: @tag, url: admin_tags_url %>
<%= render 'admin/shared/to_index_button', model_name: Tag.model_name.human, path: admin_tags_path %>

app/views/admin/tags/show.html.erb
<% content_for :title, t('.title') %>

<div class="overflow-x-auto">
  <table class="table">
    <tr>
      <th><%= Tag.human_attribute_name(:id) %></th>
      <td><%= @tag.id %></td>
    </tr>
    <tr>
      <th><%= Tag.human_attribute_name(:name) %></th>
      <td><%= @tag.name %></td>
    </tr>
    <tr>
      <th><%= Tag.human_attribute_name(:created_at) %></th>
      <td><%= l @tag.created_at, format: :long %></td>
    </tr>
    <tr>
      <th><%= Tag.human_attribute_name(:updated_at) %></th>
      <td><%= l @tag.updated_at, format: :long %></td>
    </tr>
  </table>
</div>
<div class="text-right">
  <%= render 'admin/shared/edit_and_delete_buttons', edit_path: edit_admin_tag_path(@tag), delete_path: admin_tag_path(@tag) %>
</div>
<%= render 'admin/shared/to_index_button', model_name: Tag.model_name.human, path: admin_tags_path %>